name: Manual Trigger Example

on:
  workflow_dispatch:  # Enables manual trigger

jobs:
  say-hello:
    runs-on: self-hosted
    steps:
      - name: Print Hello
        run: echo "Hello from a manually triggered workflow!"
