name: Manual Trigger

on:
  workflow_dispatch:  # Manual trigger for safety

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        run: actions/checkout@v3

      - name: build file
        run: echo "successfully triggered"
     
